#!/usr/bin/env python3

import os
import sys
import glob

command = "ct discovery -a $alignment_file -t $trait_file -o $output_file --fmt $alignment_format"
further_options = "--max_fg_gaps 0 --max_bg_gaps 0 --max_fg_miss 0 --max_fg_miss 0"

# Import the settings from arguments

trait_file = sys.argv[1]
alignment_folder = sys.argv[2]
alignment_format = "phylip-relaxed"

# Process the variables

results_folder = "disco.2022"
caas_folder = results_folder + "/" + trait_file.split("/")[-1] + ".CAAS"

# Create the output folder

try:
    os.mkdir(results_folder)
except:
    pass

try:
    os.mkdir(caas_folder)
except:
    os.system("rm -r " +  caas_folder)
    os.mkdir(caas_folder)

# Replace the fixed part of the command

command = command.replace("$trait_file", trait_file)
command = command.replace("$alignment_format", alignment_format)


# Loop over folder content

for x in glob.glob(alignment_folder + "/*"):
    thefile = x.split("/")[-1]
    theoutput = caas_folder + "/" + thefile + ".caas"
    command = command.replace("$alignment_file", x)
    command = command.replace("$output_file", theoutput)

    print(command + " " + further_options)