#!/usr/bin/env python3

import os
import sys
import glob

command = "ct discovery -a $alignment_file -t $trait_file -o $output_file --fmt $alignment_format"
filtering_options = "--max_fg_gaps 0 --max_bg_gaps 0 --max_bg_miss 0 --max_fg_miss 0"

# Import the settings from arguments

traits_folder = "../augustloop/final_configs"                               
active_traits = "../augustloop/configs.to.scan.list"                        
alignment_folder = "../augustloop/alignments"                         
alignment_format = "phylip-relaxed"

# Index the active traits

with open(active_traits, "r") as at_handle:
    at = at_handle.read().splitlines()

trait_index = {}

n = 0

for line in at:
    n += 1
    tag = str(n)
    path = traits_folder + "/" + line
    trait_index[tag] = path

try:
    trait_file = trait_index[sys.argv[1]]
except:
    print("Trait number not found")

# Process the variables

results_folder = "../augustloop/results"                                      

caas_folder = results_folder + "/" + trait_file.split("/")[-1] + ".CAAS"

# Create the output folder

try:
    os.mkdir(results_folder)
except:
    pass

try:
    os.mkdir(caas_folder)
except:
    os.system("rm -r " +  caas_folder)

    os.mkdir(caas_folder)

# Replace the fixed part of the command - one

command = command.replace("$trait_file", trait_file)
command = command.replace("$alignment_format", alignment_format)


# Loop over folder content for third condition

counter = 1
total = len(glob.glob(alignment_folder + "/*"))

for x in glob.glob(alignment_folder + "/*"):

    thefile = x.split("/")[-1]

    print("Processing file", thefile, counter, "of", total)
    counter = counter + 1

    theoutput = caas_folder + "/" + thefile + ".caas"
    loop_command = command.replace("$alignment_file", x)
    loop_command = loop_command.replace("$output_file", theoutput)

    os.system("python " + loop_command + " " + filtering_options)